apiVersion: v1
kind: Pod
metadata:
  name: gpu-zombie-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
      command: ["/bin/bash","-c", "sleep infinity"] # do nothing
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  - key: vodascheduler/hostname
    operator: Exists
    effect: NoExecute